### PR TITLE
fix(Core): Replace deprecated CIEmailField with EmailField

### PR DESCRIPTION
**Pull request by cheikhgwane**
Fix warning on deprecated CIEmailField.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Create a new case_insensitive collation.
- Replace CIEmailField  by EmailField

### CODE REVIEW

**Comment by pvanliefland** [comment]
@cheikhgwane have you seen this blog post? https://adamj.eu/tech/2023/02/23/migrate-django-postgresql-ci-fields-case-insensitive-collation/

**Comment by pvanliefland** [comment]
And https://docs.djangoproject.com/fr/4.2/ref/contrib/postgres/operations/#manage-postgresql-collations

**Comment by cheikhgwane** [comment]
> @cheikhgwane have you seen this blog post? https://adamj.eu/tech/2023/02/23/migrate-django-postgresql-ci-fields-case-insensitive-collation/

Yes, I've followed most of the steps. The problem is with the test database. It seems like the migration for adding the collation is not applied.

**Review by pvanliefland — APPROVED** [review]
LGTM - but I will merge this one when I'm back from holiday, there's no rush

**Pull request merged**
