### PR TITLE
feat(Workspaces): change workspace database password

### PR DESCRIPTION
**Pull request by cheikhgwane**
Allow a workspace admin to change the workspace database by generating a new one.

## Changes

Please list / describe the changes in the codebase for the reviewer(s).

- Increase default password length to 16
- Add api for updating a database role password.
- Create mutation for generating a new password given a workspace

### CODE REVIEW

**Comment by cheikhgwane** [comment]
@pvanliefland For the update password API I was hesitating between the current implementation or using it directly from the mutation resolver and then doing something like 

```python
update_database_password(workspace.db_name,random_generated_pwd)
workspace.set_password(new_password)
workspace.save()
```
WDYT?

**Comment by pvanliefland** [comment]
> @pvanliefland For the update password API I was hesitating between the current implementation or using it directly from the mutation resolver and then doing something like
> 
> ```python
> update_database_password(workspace.db_name,random_generated_pwd)
> workspace.set_password(new_password)
> workspace.save()
> ```
> 
> WDYT?

I think this could be encapsulated in a `generate_new_database_password` method on the `Workspace` model.

(the `update_database_password` function would be called from this method)

**Review by pvanliefland — COMMENTED** [review]
I'm wondering how your tests pass...

In `test_schema.py`, the mutation is called `generateNewDatabasePassword`.

In `schema.graphql`, it is called `generateDatabaseNewPassword`.

Are you sure your tests are run?

**Comment by cheikhgwane** [comment]
> I'm wondering how your tests pass...
> 
> In `test_schema.py`, the mutation is called `generateNewDatabasePassword`.
> 
> In `schema.graphql`, it is called `generateDatabaseNewPassword`.
> 
> Are you sure your tests are run?

Hum quite weird. Let me check

**Review by pvanliefland — APPROVED** [review]
LGTM

**Pull request merged**
